language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database currency;' -U postgres
  - psql -c 'CREATE USER currency;' -U postgres
script:
  - flake8 ./src
  - flake8 ./parse_workua
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - python ./src/manage.py makemigrations --check --dry-run
  - pip check
  - pytest ./src/tests -s
