language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
before_install:
  - sudo -u postgres psql -c "CREATE USER currency WITH PASSWORD 'currency'"
  - sudo -u postgres psql -c "ALTER ROLE currency SUPERUSER"
services:
  - postgresql
script:
  - flake8 ./src
  - flake8 ./parse_workua
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - python ./src/manage.py makemigrations --check --dry-run
  - pip check
  - pytest ./src/tests -s
