language: python

python:
  - "3.8"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.example .env
script:
  - flake8 ./src
  - flake8 ./parse_workua
  - python ./src/manage.py makemigrations --check --dry-run
  - python ./src/manage.py migrate
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - pip check
  - pytest ./src/tests -s