language: python
python:
  - "3.6"
env:
  - SECRET_KEY=*
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - flake8 ./parse_workua
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - python ./src/manage.py makemigrations --check --dry-run
  - pip check
  - pytest ./src/tests -s
