language: python

python:
  - "3.8"
services:
  - docker
before_script:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - python ./commands/deploy.sh
script:
  docker exec backend ./commands/check.sh
