language: python

python:
  - "3.8"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c "CREATE DATABASE $POSTGRES_DB;" -U postgres
  - psql -c "CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';" -U postgres
  - cp .env.example .env
script:
  - flake8 ./src
  - flake8 ./parse_workua
  - python ./src/manage.py makemigrations --check --dry-run
  - python ./src/manage.py migrate
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - pip check
  - pytest ./src/tests -s