language: python
python:
  - "3.6"
env:
  - RABBITMQ_DEFAULT_USER=*
  - RABBITMQ_DEFAULT_PASS=*
  - POSTGRES_USER=*
  - POSTGRES_PASSWORD=*
  - SECRET_KEY=*
  - EMAIL_HOST_USER=*
  - EMAIL_HOST_PASSWORD=*
  - SERVER=*
  - ALLOWED_HOSTS=*
  - DOMAIN=*
  - EMAIL_HOST=*
  - EMAIL_PORT=*
  - EMAIL_USE_TLS=*
  - EMAIL_BACKEND=*
  - DEFAULT_FROM_EMAIL=*
  - RABBITMQ_DEFAULT_HOST=*
  - MEMCACHED_HOST=*
  - POSTGRES_DB=*
  - POSTGRES_HOST=*
  - hostname=*
before_script:
  - cp .env.example .env
  - python ./src/manage.py migrate
install:
  - pip install -r requirements.txt
script:
  - flake8 ./src
  - flake8 ./parse_workua
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - python ./src/manage.py makemigrations --check --dry-run
  - pip check
  - pytest ./src/tests -s
