language: python
python:
  - "3.8"
services:
  - postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database currency;' -U postgres
  - sudo -u postgres psql -c "ALTER ROLE postgres SUPERUSER"
script:
  - flake8 ./src
  - flake8 ./parse_workua
  - python ./src/manage.py makemigrations --check --dry-run
  - python ./src/manage.py validate_templates
  - python ./src/manage.py check
  - pip check
  - pytest ./src/tests -s -x --cov-config=.coveragerc --cov=src --cov-report html --cov-fail-under=100
after_success:
  - bash <(curl -s https://codecov.io/bash)
