# Generated by Django 2.2.12 on 2020-06-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'get_latest_by': 'created'},
        ),
    ]
